// Generated by CoffeeScript 1.3.3
(function() {
  var commander, path;

  commander = require('commander');

  path = require('path');

  commander.version('0.2.1').usage('[options] [dir]').option('-a, --address <string>', 'set hostname [localhost]').option('-f, --format <string>', 'connect logger format [dev]', 'dev').option('-p, --port <number>', 'set port number [3000]', 3000);

  commander.on('--help', function() {
    return console.log('\  Examples:\n\n    Serve the current directory\n\n      $ cd /var/www\n      $ workit\n      Serving /var/www at http://localhost:3000/\n\n    Serve a specific directory\n\n      $ workit /var/www/foo\n      Serving /var/www/foo at http://localhost:3000/\n\n    Serve a specific directory with options\n\n      $ workit -a 192.168.0.1 -p 8080 /var/www/foo\n      Serving /var/www/foo at http://192.168.0.1:8080/');
  });

  commander.parse(process.argv);

  commander.dir = path.resolve(commander.args.shift());

  require('../lib/workit')(commander);

}).call(this);
