// Generated by CoffeeScript 1.3.3
(function() {
  var hound, socketio;

  hound = require('hound');

  socketio = require('socket.io');

  module.exports = function(_arg) {
    var dir, dog, io, reload, server;
    dir = _arg.dir, server = _arg.server;
    io = socketio.listen(server);
    dog = hound.watch(dir);
    reload = function() {
      return io.sockets.emit('workit-reload');
    };
    dog.on('create', reload);
    dog.on('change', reload);
    dog.on('delete', reload);
    return function(_arg1, res, next) {
      var url;
      url = _arg1.url;
      if (url !== '/workit.js') {
        return next();
      }
      res.setHeader('Content-Type', 'text/javascript');
      return res.end("      io.connect('/').on('workit-reload', function () {        document.location.reload(true);      });");
    };
  };

}).call(this);
