// Generated by CoffeeScript 1.3.3
(function() {
  var Snockets, compile, helper;

  helper = require('./helper');

  Snockets = require('snockets');

  compile = function(filename, data, cb) {
    return new Snockets().getConcatenation(filename, cb);
  };

  module.exports = function(dir) {
    return helper(dir, /\.js$/, '.coffee', compile);
  };

}).call(this);
