// Generated by CoffeeScript 1.3.3
(function() {
  var extension, fs, path, stylus;

  fs = require('fs');

  stylus = require('stylus');

  path = require('path');

  extension = /\.css$/;

  module.exports = function(dir) {
    return function(_arg, res, next) {
      var content, filename, url;
      url = _arg.url;
      if (!extension.test(url)) {
        return next();
      }
      filename = path.join(dir, url.replace(extension, '.styl'));
      if (!fs.existsSync(filename)) {
        return next();
      }
      try {
        content = fs.readFileSync(filename, 'utf8');
        return stylus.render(content, {
          filename: filename
        }, function(err, css) {
          if (err) {
            throw err;
          }
          res.setHeader('Content-Type', 'text/css');
          return res.end(css);
        });
      } catch (err) {
        return next(err);
      }
    };
  };

}).call(this);
