// Generated by CoffeeScript 1.3.3
(function() {
  var compile, helper, nib, stylus;

  helper = require('./helper');

  nib = require('nib');

  stylus = require('stylus');

  compile = function(filename, data, cb) {
    return stylus(data).set('filename', filename).use(nib()).render(cb);
  };

  module.exports = function(dir) {
    return helper(dir, /\.css$/, '.styl', compile);
  };

}).call(this);
