// Generated by CoffeeScript 1.3.3
(function() {
  var coffee, extension, fs, path;

  coffee = require('coffee-script');

  fs = require('fs');

  path = require('path');

  extension = /\.js$/;

  module.exports = function(dir) {
    return function(_arg, res, next) {
      var content, filename, url;
      url = _arg.url;
      if (!extension.test(url)) {
        return next();
      }
      filename = path.join(dir, url.replace(extension, '.coffee'));
      if (!fs.existsSync(filename)) {
        return next();
      }
      try {
        content = fs.readFileSync(filename, 'utf8');
        return res.end(coffee.compile(content, {
          filename: filename
        }));
      } catch (e) {
        return next(e);
      }
    };
  };

}).call(this);
