// Generated by CoffeeScript 1.3.3
(function() {
  var coffee, extension, fs, path;

  coffee = require('coffee-script');

  fs = require('fs');

  path = require('path');

  extension = /\.js$/;

  module.exports = function(dir) {
    return function(_arg, res, next) {
      var content, filename, js, url;
      url = _arg.url;
      if (!extension.test(url)) {
        return next();
      }
      filename = path.join(dir, url.replace(extension, '.coffee'));
      if (!fs.existsSync(filename)) {
        return next();
      }
      try {
        content = fs.readFileSync(filename, 'utf8');
        js = coffee.compile(content, {
          filename: filename
        });
        res.setHeader('Content-Type', 'text/javascript');
        return res.end(js);
      } catch (err) {
        return next(err);
      }
    };
  };

}).call(this);
