// Generated by CoffeeScript 1.3.3
(function() {
  var compile, helper, stylus;

  helper = require('./helper');

  stylus = require('stylus');

  compile = function(filename, data, cb) {
    return stylus.render(data, {
      filename: filename
    }, cb);
  };

  module.exports = function(dir) {
    return helper(dir, /\.css$/, '.styl', compile);
  };

}).call(this);
