// Generated by CoffeeScript 1.3.3
(function() {
  var extension, fs, jade, path;

  fs = require('fs');

  jade = require('jade');

  path = require('path');

  extension = /\.html?$/;

  module.exports = function(dir) {
    return function(_arg, res, next) {
      var content, filename, fn, url;
      url = _arg.url;
      if (url.slice(-1) === '/') {
        url += 'index.html';
      }
      if (!extension.test(url)) {
        return next();
      }
      filename = path.join(dir, url.replace(extension, '.jade'));
      if (!fs.existsSync(filename)) {
        return next();
      }
      try {
        content = fs.readFileSync(filename, 'utf8');
        fn = jade.compile(content, {
          filename: filename
        });
        res.setHeader('Content-Type', 'text/html');
        return res.end(fn());
      } catch (e) {
        return next(e);
      }
    };
  };

}).call(this);
