// Generated by CoffeeScript 1.3.3
(function() {
  var compile, helper, jade;

  helper = require('./helper');

  jade = require('jade');

  compile = function(filename, data, cb) {
    return cb(null, jade.compile(data, {
      filename: filename,
      pretty: true
    })());
  };

  module.exports = function(dir) {
    return helper(dir, /\.html?$/, '.jade', compile);
  };

}).call(this);
