// Generated by CoffeeScript 1.3.3
(function() {
  var http, https, url;

  http = require('http');

  https = require('https');

  url = require('url');

  module.exports = function(req, res, next) {
    var left, mod, opts, right;
    left = req.url.slice(0, 14);
    right = req.url.slice(14);
    res.setHeader('Access-Control-Allow-Origin', '*');
    if (left !== '/connect-cors/') {
      return next();
    }
    opts = url.parse(right);
    opts.headers = req.headers;
    mod = opts.protocol === 'https:' ? https : http;
    return mod.get(opts, function(res2) {
      var k, _i, _len, _ref;
      _ref = Object.keys(res2.headers);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        k = _ref[_i];
        res.setHeader(k, res2.headers[k]);
      }
      return res2.pipe(res);
    });
  };

}).call(this);
