// Generated by CoffeeScript 1.3.3
(function() {
  var connect, flow, fs, path;

  connect = require('connect');

  flow = require('flow');

  fs = require('fs');

  path = require('path');

  module.exports = function(dir, match, extension, compile) {
    return function(_arg, res, next) {
      var filename, url;
      url = _arg.url;
      if (url.slice(-1) === '/') {
        url += 'index.html';
      }
      if (url.slice(-extension.length) === extension) {
        res.setHeader('Content-Type', 'text/plain');
      }
      if (!match.test(url)) {
        return next();
      }
      filename = path.join(dir, url.replace(match, extension));
      return flow.exec(function() {
        return fs.exists(filename, this);
      }, function(exists) {
        if (!exists) {
          return next();
        }
        return fs.realpath(filename, this);
      }, function(err, real) {
        if (err) {
          return next(err);
        }
        filename = real;
        return fs.readFile(filename, 'utf8', this);
      }, function(err, data) {
        if (err) {
          return next(err);
        }
        return compile(filename, data, this);
      }, function(err, data) {
        if (err) {
          return next(err);
        }
        res.setHeader('Content-Type', connect["static"].mime.lookup(url));
        return res.end(data);
      });
    };
  };

}).call(this);
