// Generated by CoffeeScript 1.3.3
(function() {
  var connect, fs, path;

  connect = require('connect');

  fs = require('fs');

  path = require('path');

  module.exports = function(dir, match, extension, compile) {
    return function(_arg, res, next) {
      var filename, ins, url;
      url = _arg.url;
      if (url.slice(-1) === '/') {
        url += 'index.html';
      }
      if (url.slice(-extension.length) === extension) {
        res.setHeader('Content-Type', 'text/plain');
      }
      if (!match.test(url)) {
        return next();
      }
      filename = path.join(dir, url.replace(match, extension));
      if (!fs.existsSync(filename)) {
        return next();
      }
      try {
        ins = fs.readFileSync(filename, 'utf8');
        return compile(filename, ins, function(err, out) {
          var mime;
          if (err) {
            throw err;
          }
          mime = connect["static"].mime.lookup(url);
          res.setHeader('Content-Type', mime);
          return res.end(out);
        });
      } catch (err) {
        return next(err);
      }
    };
  };

}).call(this);
