// Generated by CoffeeScript 1.3.3
(function() {
  var coffee, connect, jade, path, stylus;

  connect = require('connect');

  path = require('path');

  coffee = require('./connect-coffee');

  jade = require('./connect-jade');

  stylus = require('./connect-stylus');

  module.exports = function(_arg) {
    var address, dir, format, port;
    address = _arg.address, dir = _arg.dir, format = _arg.format, port = _arg.port;
    return connect().use(connect.favicon()).use(connect.logger(format)).use(coffee(dir)).use(jade(dir)).use(stylus(dir)).use(connect["static"](dir)).use(connect.directory(dir)).listen(port, address, function() {
      return console.log('Serving %s at http://%s:%s', dir, address, port);
    });
  };

}).call(this);
