// Generated by CoffeeScript 1.3.3
(function() {
  var coffee, connect, jade, path, reload, stylus;

  connect = require('connect');

  path = require('path');

  coffee = require('./connect-coffee');

  jade = require('./connect-jade');

  reload = require('./connect-reload');

  stylus = require('./connect-stylus');

  module.exports = function(_arg) {
    var address, app, dir, format, port, server;
    address = _arg.address, dir = _arg.dir, format = _arg.format, port = _arg.port;
    app = connect();
    server = app.listen(port, address);
    app.use(connect.favicon()).use(connect.logger(format)).use(reload({
      dir: dir,
      server: server
    })).use(coffee(dir)).use(jade(dir)).use(stylus(dir)).use(connect["static"](dir)).use(connect.directory(dir));
    return console.log('Serving %s at http://%s:%s/', dir, address, port);
  };

}).call(this);
